vars:
  DOCKER_IMAGE: docker.io/planetrio/chrome-headless

tasks:
  default:
    cmds: 
      - loop:
        kafka: ["localhost:9092", "planetr-topic"]
        run: capture
        parallel: 2
  
  capture:
    cmds:
      - echo "Capture screenshot - {{.ARG}}"
      - |
        DCUID=""
        while [ -z "$DCUID" ]
        do
          DCUID=`planetr dcu-run -w {{.DOCKER_IMAGE}} g.medium`
        done
        echo DCUID:$DCUID
        planetr dcu-exec $DCUID "chrm --no-sandbox --screenshot --hide-scrollbars {{.ARG}}"
        planetr dcu-cp-from $DCUID /usr/src/screenshot.png ./screen-{{.INDX}}.png
        planetr dcu-rm $DCUID
      - echo "Capture screenshot - {{.ARG}} done."
